[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "spacey-bundle"
version = "0.0.3"
requires-python = ">=3.12"

[tool.setuptools.packages.find]
where = ["pysrc"]